project:
  type: website
  output-dir: docs

website:
  title: "orcaIntranetWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: orcaDatabase/orcaDatabaseMain.qmd
        text: "ORCA Database"
      - about.qmd
  sidebar: 
    contents: 
      - orcaDatabase/orcaDatabaseMain.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
  pdf: 
    toc: true
editor: visual

