project:
  type: book
  output-dir: docs
knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false
book:
  title: "mybook"
  author: "Jane Doe"
  date: "8/18/2021"
  downloads: [pdf,epub]
  chapters:
    - index.qmd
    - orcaDatabaseMain.qmd
    - geotek.qmd
lightbox: True
format:
  html:
    theme: cosmo
    self-contained: true
  pdf:
    documentclass: scrreprt  

